In [ ]:
import numpy as np 
import pandas as pd
from google.colab import drive

In [ ]:
drive.mount('/gdrive', force_remount = True)

Mounted at /gdrive


In [ ]:
df = pd.read_csv('/gdrive/MyDrive/0620.csv', sep = ",", low_memory=False)

In [ ]:
df

time  Dst Port  Protocol  Flow Duration  Tot Fwd Pkts  \
0        08:33:25      80.0       6.0        37953.0           5.0   
1        08:33:06     500.0      17.0    117573474.0           3.0   
2        08:33:06     500.0      17.0    117573474.0           3.0   
3        08:33:11     500.0      17.0     99743998.0           5.0   
4        08:33:11     500.0      17.0     99743999.0           5.0   
...           ...       ...       ...            ...           ...   
1046840  02:33:29   55484.0       6.0         1252.0           5.0   
1046841  02:33:29   57624.0       6.0        19055.0           5.0   
1046842  02:33:29   57623.0       6.0        36677.0           5.0   
1046843  02:33:29   57625.0       6.0         1849.0           5.0   
1046844  02:33:29   58120.0       6.0        20580.0           5.0   

         Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  \
0                 3.0            135.0            127.0            135.0   
1                 0.0           1500.0              0.0            500.0   
2                 0.0           1500.0              0.0            500.0   
3                 0.0           2500.0              0.0            500.0   
4                 0.0           2500.0              0.0            500.0   
...               ...              ...              ...              ...   
1046840           2.0            935.0            274.0            935.0   
1046841           2.0            935.0            341.0            935.0   
1046842           2.0            935.0            341.0            935.0   
1046843           2.0            935.0            341.0            935.0   
1046844           2.0            935.0            299.0            935.0   

         Fwd Pkt Len Min  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0                    0.0  ...              32.0          0.0         0.0   
1                  500.0  ...               8.0          0.0         0.0   
2                  500.0  ...               8.0          0.0         0.0   
3                  500.0  ...               8.0    4000290.0         0.0   
4                  500.0  ...               8.0    4000286.0         0.0   
...                  ...  ...               ...          ...         ...   
1046840              0.0  ...              20.0          0.0         0.0   
1046841              0.0  ...              20.0          0.0         0.0   
1046842              0.0  ...              20.0          0.0         0.0   
1046843              0.0  ...              20.0          0.0         0.0   
1046844              0.0  ...              20.0          0.0         0.0   

         Active Max  Active Min   Idle Mean    Idle Std    Idle Max  \
0               0.0         0.0         0.0         0.0         0.0   
1               0.0         0.0  58800000.0  23800000.0  75600000.0   
2               0.0         0.0  58800000.0  23800000.0  75600000.0   
3         4000290.0   4000290.0  31900000.0  37900000.0  75600000.0   
4         4000286.0   4000286.0  31900000.0  37900000.0  75600000.0   
...             ...         ...         ...         ...         ...   
1046840         0.0         0.0         0.0         0.0         0.0   
1046841         0.0         0.0         0.0         0.0         0.0   
1046842         0.0         0.0         0.0         0.0         0.0   
1046843         0.0         0.0         0.0         0.0         0.0   
1046844         0.0         0.0         0.0         0.0         0.0   

           Idle Min  DDOS  
0               0.0   0.0  
1        42000000.0   0.0  
2        42000000.0   0.0  
3         7200397.0   0.0  
4         7200399.0   0.0  
...             ...   ...  
1046840         0.0   0.0  
1046841         0.0   0.0  
1046842         0.0   0.0  
1046843         0.0   0.0  
1046844         0.0   0.0  

[1046845 rows x 80 columns]

In [ ]:
K = df.copy()

In [ ]:
K['time']

0          08:33:25
1          08:33:06
2          08:33:06
3          08:33:11
4          08:33:11
             ...   
1046840    02:33:29
1046841    02:33:29
1046842    02:33:29
1046843    02:33:29
1046844    02:33:29
Name: time, Length: 1046845, dtype: object

In [ ]:
K['time'].replace(':','',regex=True, inplace=True)

In [ ]:
K['time'].astype('float')

0          83325.0
1          83306.0
2          83306.0
3          83311.0
4          83311.0
            ...   
1046840    23329.0
1046841    23329.0
1046842    23329.0
1046843    23329.0
1046844    23329.0
Name: time, Length: 1046845, dtype: float64

In [ ]:
test = K[['Fwd Header Len', 'Tot Fwd Pkts', 'Fwd Seg Size Avg', 
             'Subflow Fwd Byts', 'Init Bwd Win Byts', 'Fwd Pkt Len Std', 'Flow IAT Std', 
            'Bwd IAT Min', 'Bwd Seg Size Avg', 'ACK Flag Cnt', 'Tot Bwd Pkts', 'Bwd Pkt Len Mean', 'Pkt Len Mean', 
         'Pkt Len Max', 'Subflow Bwd Pkts', 'Flow IAT Min', 'TotLen Bwd Pkts', 'Bwd Pkt Len Std', 'Flow IAT Max', 'Flow Duration', 'Fwd IAT Tot', 'DDOS']]

In [ ]:
test = test.sample(frac=0.1)

In [ ]:
x = test.drop(['DDOS'], axis =1)
y = test['DDOS']
test_dataset = test.sample(frac=0.3)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)


In [ ]:
print(x_train.shape)

print(x_test.shape)
print(y_train.shape)

print(y_test.shape)

(73278, 21)
(31406, 21)
(73278,)
(31406,)


In [ ]:
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

In [ ]:
y_train.shape

(73278,)

In [ ]:
y_test.shape

(31406,)

In [ ]:
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)

In [ ]:
y_train.shape


(73278, 1)

In [ ]:
y_test.shape

(31406, 1)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(73278, 21)
(31406, 21)
(73278, 1)
(31406, 1)


In [ ]:
y_test

array([[0.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [ ]:
y_test = pd.DataFrame(y_test)

In [ ]:
y_train = pd.DataFrame(y_train)

In [ ]:
y_test

0
0      0.0
1      1.0
2      1.0
3      1.0
4      1.0
...    ...
31401  1.0
31402  1.0
31403  1.0
31404  1.0
31405  1.0

[31406 rows x 1 columns]

In [ ]:
x_train = np.array(x_train)
y_train = np.array(y_train)

x_test = np.array(x_test)
y_test = np.array(y_test)

In [ ]:
x_train.shape

(73278, 21)

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)

(73278, 21)
(73278, 1)
(31406, 21)


In [ ]:
x_train = np.reshape(x_train, (73278, 1, 21))
x_test = np.reshape(x_test, (31406, 1, 21))

In [ ]:
x_train.shape

(73278, 1, 21)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.compat.v1.keras.layers import CuDNNLSTM

In [ ]:
model = Sequential()


model.add(CuDNNLSTM(128, input_shape=(1,21), return_sequences=True))
model.add(Dropout(0.2))

model.add(CuDNNLSTM(128))
model.add(Dropout(0.1))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(1, activation='sigmoid'))

opt = tf.keras.optimizers.Adam(lr=0.01, decay=1e-6)

model.compile(
    loss='binary_crossentropy',
    optimizer=opt,
    metrics=['accuracy'],
)

model.fit(x_train,
          y_train,
          epochs=100,
          validation_data=(x_test, y_test)
          )

Epoch 1/100


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


2290/2290 [==============================] - 24s 7ms/step - loss: 0.0183 - accuracy: 0.9963 - val_loss: 0.0063 - val_accuracy: 0.9979
Epoch 2/100
2290/2290 [==============================] - 15s 7ms/step - loss: 0.0142 - accuracy: 0.9966 - val_loss: 0.0063 - val_accuracy: 0.9979
Epoch 3/100
2290/2290 [==============================] - 15s 7ms/step - loss: 0.0184 - accuracy: 0.9949 - val_loss: 0.0068 - val_accuracy: 0.9979
Epoch 4/100
2290/2290 [==============================] - 15s 6ms/step - loss: 0.0115 - accuracy: 0.9975 - val_loss: 0.0050 - val_accuracy: 0.9980
Epoch 5/100
2290/2290 [==============================] - 15s 7ms/step - loss: 0.0122 - accuracy: 0.9978 - val_loss: 0.0130 - val_accuracy: 0.9980
Epoch 6/100
2290/2290 [==============================] - 15s 6ms/step - loss: 0.0140 - accuracy: 0.9975 - val_loss: 0.0086 - val_accuracy: 0.9979
Epoch 7/100
2290/2290 [==============================] - 15s 7ms/step - loss: 0.0124 - accuracy: 0.9974 - val_loss: 0.0084 - val_accurac

In [ ]:
loss,acc = model.evaluate(x_test, y_test, verbose = 1)

982/982 [==============================] - 3s 3ms/step - loss: 0.0044 - accuracy: 0.9980


In [ ]:
prediction = model.predict(x_test)

In [ ]:
prediction[10]

array([0.99999166], dtype=float32)

In [ ]:
threshold = 0.5

prediction_2 = np.where(prediction >= threshold, 1, prediction)
prediction_2 = np.where(prediction_2 < threshold, 0, prediction_2)

prediction_2

array([[0.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [ ]:
cm = confusion_matrix(y_test, prediction_2)
print(cm)

[[10600    62]
 [    0 20744]]


In [ ]:
print("True Negative TN : ", cm[0][0])

print("False Positive FP : ", cm[0][1])

print("False Negative FN : ", cm[1][0])

print("True Positive TP : ", cm[1][1])

True Negative TN :  10600
False Positive FP :  62
False Negative FN :  0
True Positive TP :  20744


In [ ]:
print("Detection Rate is : ", (cm[1][1])/(cm[1][1]+cm[1][0])*100)

print("False Alarm Rate is : ", (cm[0][1])/(cm[0][1]+cm[0][0])*100)

Detection Rate is :  100.0
False Alarm Rate is :  0.5815044081785782


In [ ]:
print(classification_report(y_test, prediction_2, digits=5))

              precision    recall  f1-score   support

         0.0    1.00000   0.99418   0.99708     10662
         1.0    0.99702   1.00000   0.99851     20744

    accuracy                        0.99803     31406
   macro avg    0.99851   0.99709   0.99780     31406
weighted avg    0.99803   0.99803   0.99802     31406



In [ ]:
# from keras.model import load_model

In [ ]:
model.save('0829.h5')